#!/usr/bin/env bash
# Use grep with dig to get info about an IP Address

func ()
{
	ans=$(dig "$2.$1" | grep -A1 "ANSWER SECTION:" | tail -1)
	echo "$2 $ans" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" -eq 1 ]
then
  func "$1" "www"
  func "$1" "lb-01"
  func "$1" "web-01"
  func "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  func "$1" "$2"
fi
