#!/usr/bin/env bash
# $4 is the ssh key file
# $3 is the username
# $2 is the ip address
# $1 is the file to be copied
# In a nutshell this just invokes scp with the specified arguments

val=$#

if [ "$val" -lt 4 ];then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY" >&2
  exit 1;
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi

