#!/usr/bin/env bash
# Install ngninx server & write page then restart it
# Configure redirection to a random page
sudo apt-get update -y
sudo apt-get install nginx -y

sudo echo "Hello World!" > /var/www/html/index.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.duckduckgo.com permanent";
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
