#!/usr/bin/env bash
# Configure a web server with a custom Header response
# WARN: Have not configured sed to replace existing text.
# For example if there's already a 404 configured, it won't replace the text

sudo apt-get update
sudo apt-get install nginx -y

# Configure root page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error_="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$error_/" /etc/nginx/sites-enabled/default

# Configure redirect 301 page & add a custom header
redirect_="server_name _;\n\tadd_header X-Served-By \$Hostname;\n\trewrite ^\/redirect_me https:\/\/www.duckduckgo.com permanent;"
sudo sed -i "s/server_name _;/$redirect_/" /etc/nginx/sites-enabled/default

sudo service nginx restart


