#!/usr/bin/env bash
# This script will perform a series of actions
: '
1. Create the file with the pid of the current process
2. Print to the screen & sleep for 2secs
3. Then print a message when given a SIGINT
4. Then print a message when given a SIGTERM
5. Then print a message when given a SIGQUIT
'

kill_quit() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command && terminator"' SIGTERM
  trap 'kill_quit' SIGQUIT
done


