#!/usr/bin/env bash
# The script manages a specific daemon
# Start, Stop, Restart
: '
To start the process it will create the file 
which will store its pid in a file.
From there it can manage the process using the pid within the file
'

if [ "${1}" == "start" ]; then
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid 
  echo "manage_my_process started"
elif [ "${1}" == "stop" ]; then
  echo "manage_my_process stopped"
  kill "$(cat /var/run/my_process.pid)"
  rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]; then
  kill "$(cat /var/run/my_process.pid)"
  rm /var/run/my_process.pid
  ./manage_my_process &
  echo "$!" > /var/run/my_process.pid 
  echo "manage_my_process restarted"
else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
