#!/usr/bin/env bash
# Tells the story of passwd
# Mainly its just grabbing specific values
# from the file then printing them out in a sentence

while IFS=':' read -r username gid home shell uid password info;
do
  echo "The user $username is part of the $gid,"\
    "lives in $home and rides $shell."\
    "$uid's place is protected by the passcode $password,"\
    "more info about the user here: $info"
done < "/etc/passwd"
