#!/usr/bin/env bash
# Simply Prints Best School 10 Times
# Then prints Hi on the 8th time

count=0

while [ "$count" -le 9 ]
do
  echo "Best School"
  if [ "$count" == 8 ]; then
    echo "Hi"
  fi
  count=$((count + 1))
done
