#!/usr/bin/env bash
# Simply Prints Best School 10 Times
# On the 4th time it prints bad luck
# On the 8th time it prints good luck

count=1

while [ "$count" -le 10 ]
do
  if [ "$count" == 4 ]; then
    echo "bad luck"
  elif [ "$count" == 8 ]; then
    echo "good luck"
  else 
    echo "Best School"
  fi
  count=$((count + 1))
done
