#!/usr/bin/env bash
# Simply Prints 1 - 20
# On the 4th number it prints bad luck from China
# On the 9th number it prints bad luck from Japan
# On the 17th number it prints bad luck from Italy

count=1

while [ "$count" -le 20 ]
do
  if [ "$count" == 4 ]; then
    echo "$count"
    echo "bad luck from China"
  elif [ "$count" == 9 ]; then
    echo "$count"
    echo "bad luck from Japan"
  elif [ "$count" == 17 ]; then
    echo "$count"
    echo "bad luck from Italy"
  else
    echo "$count"
  fi
  count=$((count + 1))
done
