#!/usr/bin/env bash
# Prints the time 12:59 starting from 0

hour=0

while [ "$hour" -le 12 ]
do
  echo "Hour: $hour"
  count=1 #NOTE: Declare inline here so the loop keeps running
  while [ $count -le 59 ]
  do 
    echo "$count"
    ((count++))
  done
  ((hour++))
done
