#!/usr/bin/env bash

# Install UFW & set rules

sudo apt-get update -y;
sudo apt-get install ufw -y;

sudo ufw disable
sudo ufw default deny incoming
# Only allow tcp connections
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

sudo ufw enable
