#!/usr/bin/env bash
# Configures the ip adress for in the /etc/hosts file
# Copy the hosts file into a new one, when done force copy the file back

cp /etc/hosts ~/hosts.new
echo "127.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8         facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

