#!/usr/bin/env bash

# Run nginx operations as nginx

sudo service nginx stop # just in case nginx is live
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
